language: erlang
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=74319455557abd99a9de585cf48bc99577cbac1c
  email: eng@basho.com
otp_release:
  - R15B01
  - R15B
  - R14B04
  - R14B03
