#!/bin/sh
# postinst script for riak
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    # update-rc.d riak defaults

    # remove any v1 config files left lying around
    rm -rf /etc/riak/vm.args
    rm -rf /etc/riak/app.config

    if ! getent group riak >/dev/null; then
	addgroup --system riak
    fi

    if ! getent passwd riak >/dev/null; then
	adduser --ingroup riak --home /var/lib/riak --disabled-password --system --shell /bin/bash --no-create-home --gecos riak riak
    fi

    for i in lib log; do
	chown -R riak:riak /var/$i/riak
    done

    chown -R riak:riak /usr/lib/riak
    chown -R riak:riak /etc/riak

    chmod 0644 /etc/riak/*
    chmod -R +X /etc/riak
    chmod 0755 /usr/lib/riak/lib/env.sh

    update-rc.d -f riak remove
    update-rc.d riak stop 80 0 1 6 .
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
