language: erlang
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=f298b56e20009568a29135485bca1220d0733d05
  email: eng@basho.com
otp_release:
  - R15B01
  - R15B
  - R14B04
  - R14B03
